blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogpostCreateView, BlogpostListView, BlogpostDetailView, BlogpostUpdateView, BlogpostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create', BlogpostCreateView.as_view(), name='create'),
    path('', BlogpostListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogpostDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogpostUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogpostDeleteView.as_view(), name='delete'),
]

catalog_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from catalog_app import views
from catalog_app.apps import CatalogAppConfig
from catalog_app.views import ProductCreateView, ProductUpdateView, ProductDeleteView, ProductListView, ContactsView, \
    ProductDetailView

app_name = CatalogAppConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product_update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
import django.conf
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog_app.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {"null": "True", "blank": "True"}


class Blogpost(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(unique=True, max_length=100, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blogpost/', verbose_name='изображение', **NULLABLE)
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'Публикация: {self.title}'

    class Meta:
        verbose_name = ''
        verbose_name_plural = ''
        ordering = ("-date_create",)

catalog_app/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование категории')
    description = models.TextField(verbose_name='Описание категории', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Наименование продукта')
    description = models.TextField(verbose_name='Описание продукта', **NULLABLE)
    picture = models.ImageField(upload_to='products/', verbose_name='Превью', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за покупку')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Version(models.Model):
    product = models.ForeignKey(
        Product,
        related_name="version",
        on_delete=models.CASCADE,
        **NULLABLE,
        verbose_name="Продукт",
    )
    version_number = models.PositiveIntegerField(
        verbose_name="Номер версии",
        help_text="Введите номер версии продукта",
    )
    version_title = models.CharField(
        max_length=150,
        verbose_name="Название версии",
        help_text="Введите название версии",
    )
    version_is_active = models.BooleanField(
        default=False, verbose_name="Признак текущей версии"
    )

    class Meta:
        verbose_name = "версия"
        verbose_name_plural = "версии"

    def __str__(self):
        return f"{self.version_title}"

catalog_app/forms.py
from django import forms

from catalog_app.models import Product, Version
from catalog_app.common.views import StyleFormMixin


class ProductForm(StyleFormMixin):
    class Meta:
        model = Product
        exclude = ('views_count', 'created_at', 'updated_at')

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        prohibited_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                            'радар']
        if cleaned_data in prohibited_words:
            raise forms.ValidationError('Данное слово нельзя использовать в карточке')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        prohibited_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                            'радар']
        if cleaned_data in prohibited_words:
            raise forms.ValidationError('Данное слово нельзя использовать в карточке')

        return cleaned_data


class VersionForm(StyleFormMixin):
    class Meta:
        model = Version
        fields = ('version_number', 'version_title', 'version_is_active')

catalog_app/common/views.py
from django.forms import widgets, ModelForm


class StyleFormMixin(ModelForm):
    """Миксин для стилизации форм
    """
    def __init__(self,  *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

catalog_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View, generic
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from catalog_app.forms import ProductForm, VersionForm
from catalog_app.models import Product, Category, Version

from catalog_app.models import Product


class ProductListView(generic.ListView):
    model = Product
    template_name = 'catalog_app/product_list.html'
    context_object_name = 'product_list'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        active_version = Version.objects.filter(version_is_active=True)
        context['title'] = 'Все продукты'

        active_versions = []
        for product in context['object_list']:
            version = active_version.filter(product=product)
            if version:
                active_versions.append(version[0])
        context["active_versions"] = active_versions
        return context


class ContactsView(View):
    @staticmethod
    def get(request):
        return render(request, 'catalog_app/contacts.html')


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog_app/product_detail.html'
    context_object_name = 'product'


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog_app:home')

    permission_required = 'catalog.add_product'

    extra_context = {
        'title': 'Добавление товара'
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(generic.UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog_app:home')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset

        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = self.get_context_data()['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    # def get_object(self, queryset=None):
    #     object = super().get_object(queryset)
    #     if object.owner != self.request.user:
    #         raise Http404("Вы не являетесь владельцем продукта.")
    #     return object


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog_app:home')

catalog_app/templates/catalog_app/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore: {{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog_app/includes/inc_catalog_header.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - самый известный и крупный маркетплейс в России. Здесь можно заказать всё, что вам нужно!</p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}

{% include 'catalog_app/includes/inc_catalog_footer.html' %}
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog_app/templates/catalog_app/category_list.html
{% extends 'catalog_app/base.html' %}

{% load my_tags %}

{% block content %}
<h1 class="display-4" style="text-align: center;">{{ title }}</h1>
<div class="container">

</div>
<div class="card mb-3" style="max-width: 100%;">
    {% for object in object_list %}
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{% media_tag object.image %}" class="img-fluid rounded-start" alt="Image">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h2 class="card-title">{{ object.name | title }}</h2>
                <p class="card-text">{{ object.description }}</p>
            </div>
        </div>
    </div>
    <footer class="text-muted">
        <div class="container">
            <div class="container mt-4 mb-4">
                {% if perms.catalog.add_product %}
                <a href="{% url 'catalog_app:product_create' %}" class="btn btn-primary">Добавить товар</a>
                {% endif %}
                <a href="{% url 'catalog_app:category_products' object.pk %}" class="btn btn-primary">Отобразить товары</a>
            </div>
        </div>
    </footer>
    {% endfor %}
</div>
{% endblock %}

catalog_app/templates/catalog_app/category_product_list.html
{% extends 'catalog_app/base.html' %}

{% load my_tags %}

{% block content %}
<h1 class="display-4" style="text-align: center;">{{ title }}</h1>
<div class="container">

</div>
<div class="card mb-3" style="max-width: 100%;">
    {% for object in object_list %}
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{% media_tag object.image %}" class="img-fluid rounded-start" alt="Image">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h2 class="card-title">{{ object.name }}</h2>
                <p class="card-text">{{ object.description }}</p>
            </div>
        </div>
    </div>
    <footer class="text-muted">
        <div class="container">
            <div class="container mt-4 mb-4">

                {% if object.owner == request.user or user.is_superuser or user.is_staff %}
                {% if perms.catalog.view_product %}
                <a href="{% url 'catalog_app:product' object.pk %}" class="btn btn-primary">Подробности</a>
                {% endif %}

                {% if perms.catalog.change_product %}
                <a href="{% url 'catalog_app:product_update' object.pk %}" class="btn btn-primary">Изменить товар</a>
                {% endif %}

                {% endif %}
            </div>
        </div>
    </footer>
    {% endfor %}
</div>
{% endblock %}

catalog_app/templates/catalog_app/contacts.html
{% extends 'catalog_app/base.html' %}

{%block title%} {{ title }} {%endblock%}

{%block content%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <div class="row text-center">
                            <button type="submit" class="form-control btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog_app/templates/catalog_app/home.html
{% extends 'catalog_app/base.html' %}

{% load my_tags %}

{% block title %}Домашняя страница{% endblock %}

{% block content %}

<!-- Здесь выводим список товаров -->
<div class="container mt-5">
    <h2>Список товаров</h2>
    <div class="row">
        {% for product in products %}
        <div class="col-3">
            <div class="card mb-3">
                <img src="{{ product.picture|media_path }}" class="card-img-top" alt="{{ product.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description|slice:":100" }}</p>
                    <p class="card-text">Цена: {{ product.price }}</p>
                </div>
                <a href="{% url 'catalog_app:product_detail' product.pk %}" class="btn btn-primary">Подробнее</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog_app/templates/catalog_app/index.html
{% extends 'catalog_app/base.html' %}
{% load mytags%}
{% load static %}
{% block content %}

<div class="album py-5 bg-light">
        <div class="container">
            <div class="button">
                <p><a class="btn btn-secondary" href="{% url 'catalog_app:product_create' %}" role="button">Создать продукт &raquo;</a></p>
                <div class="row">
                    {% for object in object_list %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top" src="{% media_path object.image %}" alt="Изображение недоступно" width="304" height="228">
                                <div class="card-body">
                                    <p class="card-text">{{ object }}{{ object.category }}.</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        {% if user.is_authenticated %}
                                         <div class="btn-group">
                                                    <p><a class="btn btn-secondary" href="{% url 'catalog_app:product_detail' pk=object.id %}" role="button">Подробнее &raquo;</a></p>
                                                    {% if perms.catalog.change_product %}
                                                    <p><a class="btn btn-secondary" href="{% url 'catalog_app:product_update' object.id %}" role="button">Изменить &raquo;</a></p>
                                                    {% endif %}
                                                    {% if user.is_superuser %}
                                                    <p><a class="btn btn-secondary" href="{% url 'catalog_app:product_delete' object.id %}" role="button">Удалить &raquo;</a></p>
                                                    {% endif %}
                                                </div>
                                        {% else %}

                                        {% endif %}
                                        <small class="text-muted">{{ object.creat_date}}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>>
        </div>
</div>
{% endblock %}

catalog_app/templates/catalog_app/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <div class="container">
        <a class="navbar-brand" href="#">FreshMarket</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'catalog_app:home' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'catalog_app:contacts' %}">Контакты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'catalog_app:blogpost_list' %}">Блог</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

catalog_app/templates/catalog_app/product_confirm_delete.html
{% extends 'catalog_app/base.html' %}

{% block content %}
<div class="col">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Удаление продукта</h5>
      <form method="post">
        {% csrf_token %}
        Подтвердите удаление продукта"{{ object.name }}"<br>
        <input type="submit" class="btn btn-outline-danger" value="Подтверждаю">
      </form>
      <div class="card-footer">
        <a href="{% url 'catalog_app:home' %}" class="btn btn-primary"><< Назад</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

catalog_app/templates/catalog_app/product_detail.html
{% extends 'catalog_app/base.html' %}

{% load my_tags %}
{%block title%} title {%endblock%}

{%block content%}
<div class="card mb-3" style="max-width: 100%;">
  <div class="row g-0">
    <div class="col-md-4">
<!--      <img src="/media/{{ object.image }}" class="img-fluid rounded-start" alt="...">-->
<!--      <img src="{{ object.image | media_path }}" class="img-fluid rounded-start" alt="...">-->
      <img src="{% media_tag object.picture %}" class="img-fluid rounded-start" alt="Image">

    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h2 class="card-title">{{ object.name | title }}</h2>
        <p class="card-text">{{ object.description }}</p>
        <p class="card-text"><small class="text-body-secondary">дата публикации: {{ object.time_create }}</small></p>
        <p class="card-text"><small class="text-body-secondary">владелец: {{ object.owner|default:"нет владельца" }}</small></p>
        <h4 class="my-0 font-weight-normal">Цена {{ object.price }} руб.</h4><br>
        <a href="#" class="btn btn-primary">купить</a>
      </div>
    </div>
  </div>
</div>
<div>
<footer class="text-muted">
    <div class="container">
        <div class="container">
            {% if object.owner == request.user or user.is_superuser or user.is_staff %}
            {% if perms.catalog.delete_product %}
            <a href="{% url 'catalog_app:product_delete' object.pk %}" type="button" class="btn btn-danger">Удалить</a>
            {% endif %}
            {% if perms.catalog.change_product %}
            <a href="{% url 'catalog_app:product_update' object.pk %}" class="btn btn-primary">Изменить товар</a>
            {% endif %}
            <a href="{% url 'catalog_app:home' %}" class="btn btn-primary">Назад к списку</a>

            {% for version in active_versions %}
            {% if version.product_id == object.pk %}
            <p style="font-weight: bold; color: red;">Активная версия:
                {{ version.version_number }} - {{ version.version_name }}</p>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
</footer>
</div>
{%endblock%}

catalog_app/templates/catalog_app/product_form.html
{% extends 'catalog_app/base.html' %}

{% block content %}
<form class="row" method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                {{ title }}
                {% else %}
                {{ title }}
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p}}
                <button type="submit" class="btn btn-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                <a href="{% url 'catalog_app:home' %}" class="btn btn-primary">Отмена</a>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
    {% if object %}
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {{ title }}
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
</form>
{% endblock %}

catalog_app/templates/catalog_app/product_list.html
{% extends 'catalog_app/base.html' %}

{% load my_tags %}

{% block content %}
<h1 class="display-4" style="text-align: center;">Товары</h1>
<div class="container">
    {% if perms.catalog.add_product %}
    <a href="{% url 'catalog_app:product_create' %}" class="btn btn-primary mb-5">Добавить товар</a>
    {% endif %}
</div>
<div class="card mb-3" style="max-width: 100%;">
    {% for object in object_list %}
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{% media_tag object.picture %}" class="img-fluid rounded-start" alt="Image">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h2 class="card-title">{{ object.name | title }}</h2>
                <p class="card-text">{{ object.description | truncatechars:100 }}</p>
            </div>
        </div>
    </div>
    <footer class="text-muted">
        <div class="container">
            <div class="container mt-4 mb-4">
                {% if object.owner == request.user or user.is_superuser or user.is_staff %}
                {% if perms.catalog.view_product %}
                <a href="{% url 'catalog_app:product_detail' object.pk %}" class="btn btn-primary">Подробности</a>
                {% endif %}

                {% if perms.catalog.change_product %}
                <a href="{% url 'catalog_app:product_update' object.pk %}" class="btn btn-primary">Изменить товар</a>
                {% endif %}

                {% for version in active_versions %}
                        {% if version.product == object %}
                            <p style="font-weight: bold; color: red;">Активная версия:
                                {{ version.version_number }} - {{ version.version_title }}</p>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </footer>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}